name: Generate sitemap-style files.json

permissions:
  contents: write  # allow workflow to push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # use PAT instead of default GITHUB_TOKEN

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Generate sitemap-style JSON
      - name: Generate sitemap files.json
        run: |
          python3 - <<'EOF'
          import os, json

          GITHUB_BASE_URL = "https://codebyshivu.github.io/backend/"
          ROOT = "."  # scan entire repo

          sitemap = {}

          for root_dir, dirs, files in os.walk(ROOT):
              for f in files:
                  # Include all relevant file types
                  if f.endswith(('.txt', '.mp3', '.json', '.md')):  # extend as needed
                      rel_path = os.path.relpath(os.path.join(root_dir, f), ROOT)
                      github_url = GITHUB_BASE_URL + rel_path.replace("\\", "/")
                      
                      # Use first folder as key, or "root" if in root
                      parts = rel_path.split(os.sep)
                      folder = parts[0] if len(parts) > 1 else "root"

                      if folder not in sitemap:
                          sitemap[folder] = []
                      sitemap[folder].append(github_url)

          # Write JSON at repo root
          with open("files.json", "w", encoding="utf-8") as fp:
              json.dump(sitemap, fp, indent=4, ensure_ascii=False)

          print(f"✅ files.json sitemap generated with {sum(len(v) for v in sitemap.values())} files")
          EOF

      # Step 4: Commit and push using PAT
      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$GH_PAT" ]; then
            echo "❌ GitHub PAT is missing! Please create secret GH_PAT."
            exit 1
          fi

          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add files.json
          git commit -m "Auto update sitemap-style files.json" || echo "No changes"
          git push https://$GH_PAT@github.com/${{ github.repository }} HEAD:main
