name: Update song.json using PAT

on:
  workflow_dispatch:  # Run manually
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Create or update song.json directly
      - name: Write song.json
        run: |
          echo '["https://codebyshivu.github.io/backend/Song/chalisa/song1.mp3","https://codebyshivu.github.io/backend/Song/chalisa/song2.mp3"]' > song.json

      - name: Commit & push using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.name "GitHub PAT Bot"
          git config --local user.email "actions@github.com"
          git add song.json
          git commit -m "Update song.json [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:$GH_PAT@github.com/${{ github.repository }} HEAD:main
