name: Generate files.json

# Allow the workflow to write to repo
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # do NOT use default GITHUB_TOKEN

      # Step 2: Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Generate files.json
      - name: Generate files.json
        run: |
          python3 - <<'EOF'
          import os, json

          GITHUB_BASE_URL = "https://codebyshivu.github.io/backend/"
          LOCAL_BASE_PATH = ".appdata/"
          ROOT = "backend"  # change to "." if files are in root

          files = []
          for root, dirs, fs in os.walk(ROOT):
              for f in fs:
                  if f.endswith(('.txt', '.mp3', '.json')):
                      rel_path = os.path.relpath(os.path.join(root, f), ROOT)
                      github_url = GITHUB_BASE_URL + rel_path.replace("\\", "/")
                      folder = rel_path.split("/")[0].lower()
                      local_path = f"{LOCAL_BASE_PATH}.{folder}/{f}"
                      files.append({"url": github_url, "path": local_path})

          data = {"files": files}
          os.makedirs(ROOT, exist_ok=True)
          with open(os.path.join(ROOT, "files.json"), "w", encoding="utf-8") as fp:
              json.dump(data, fp, indent=4, ensure_ascii=False)

          print("✅ files.json created in backend/")
          EOF

      # Step 4: Commit and push using PAT
      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "$GH_PAT" ]; then
            echo "❌ GitHub PAT is missing! Please create secret GH_PAT in your repo."
            exit 1
          fi

          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add backend/files.json
          git commit -m "Auto update files.json" || echo "No changes"
          git push https://$GH_PAT@github.com/${{ github.repository }} HEAD:main
