name: Generate songs.json

on:
  workflow_dispatch: # Can run manually
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios cheerio fs

      - name: Generate songs.json
        run: node scripts/generate_songs.js

      - name: Commit and push songs.json
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add songs.json
          git commit -m "Update songs.json [skip ci]" || echo "No changes to commit"
          git push
