name: Generate song.json

on:
  push:
    branches: [ main ]
    paths:
      - "Song/chalisa/**"
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Generate song.json
      - name: Generate song list
        run: |
          mkdir -p Song/chalisa
          echo "[" > song.json
          first=true
          for file in Song/chalisa/*.mp3; do
            if [ -f "$file" ]; then
              base=$(basename "$file" .mp3)
              clean_name=$(echo "$base" | sed 's/_/ /g')
              url="https://codebyshivu.github.io/backend/$file"

              if [ "$first" = true ]; then
                first=false
              else
                echo "," >> song.json
              fi

              echo "  {\"name\": \"$clean_name\", \"url\": \"$url\"}" >> song.json
            fi
          done
          echo "]" >> song.json

          # Format JSON (prettify)
          jq '.' song.json > tmp.json && mv tmp.json song.json

          cat song.json

      # 3️⃣ Commit and push back
      - name: Commit and push song.json
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add song.json
          git commit -m "Auto-update song.json" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git HEAD:main
